Add grab_obs_id function
lsst-ts/ts_utils pull request #8
Opened 2022-12-01 17:54 UTC by couger01

2022-12-01 18:18 UTC, patrickingraham commented on python/lsst/ts/utils/generator.py
> +    site : `str`
@tribeiro should chime in but the site aspects should all be available from the deployment environment. There should be no need to pass it any information.

2022-12-01 18:20 UTC, patrickingraham commented on python/lsst/ts/utils/generator.py
> +            url = "http://139.229.170.11/"
this stuff needs to live in a config file somewhere and not in a method.
I think this is the reason it's better to use a class. Essentially it gets configured on the init and then there is no need to pass anything back and forth each time you need a obsID

2022-12-01 18:20 UTC, patrickingraham commented on python/lsst/ts/utils/generator.py
> +    """Get observing sequence IDs from image service
remove "sequence" as it's a loaded term that's going to add confusion.

2022-12-01 18:21 UTC, patrickingraham commented on python/lsst/ts/utils/generator.py
> +async def grab_obs_id(site: str, csc: BaseCsc, num_images: int) -> tuple:
Consider "get" instead as it is more compatible with other methods.

2022-12-02 22:28 UTC, tribeiro requested changes
I think there was a bit of a misunderstanding in the interpretation of the ticket request. As it says there "Create an obsID grabbing *class* in ts_utils", emphasis in the "class" part. I don't think this method is a good design, especially the part where we have to pass in the CSC object. 

What I had in mind was something like this, you make a class that the user instantiate with all the information needed to access and configure the server, then add a method in the class to retrieve the information. Something like this:

```
class IndexClient:
    """Client to retrieve unique index for a component... 

    (add more description here about the class)
    """

    def __init__(self, id: str, url: str, ...):
        ....

    async def get_names_seqnum(self, num_images: int, ...) ->tuple[list[str], list[int]]:
        """Retrieve the names and sequence number for a number of images.

        Parameters
        -----------
        num_images: `int`
            The number of images to request names/seqnum for.

        Returns
        -------
        image_names: `list`
            The set of image names returned from the service.
        image_sequence_array: `list`
            The set of SEQNUMs for the requested images.
        """
        ....
```

2022-12-03 00:52 UTC, r-owen commented on python/lsst/ts/utils/generator.py
> +    site : `str`
That makes a lot of sense to me: store it in an environment variable. Which I know are a nuisance for deployment, but the thought of ts_utils having its own configuration file is disturbing!'

What should this function do at sites which do not have access to the required service? That strongly makes me think this belongs in some other package than ts_utils.

2022-12-03 01:02 UTC, r-owen commented on python/lsst/ts/utils/generator.py
> +    site : `str`
This function probably this belongs in some other package than ts_utils. ts_utils has few dependencies and aiohttp was not one of them.

Also note that aiohttp is not well maintained. It has not had a release since 2019. I am very leery of having new code rely on it. I do not know of another asyncio-friendly version of requests, alas (I wish the standard library had something). One option is to use the `requests` package itself and wrap the call in `run_in_executor`. That is a big messy, but `requests` is well maintained so it may be worth the hassle.

2022-12-05 14:56 UTC, tribeiro requested changes
Alright! This is a considerable improvement over the previous version I just have a couple more changes I think you could to generalize the client.

2022-12-05 14:56 UTC, tribeiro commented on doc/version_history.rst
> +* Add ImageNameServiceClient class
Can you update the version number and make is 1.2.0? The version is still not set but I think this change makes it 1.2. We may want to wait for Russell's other PR #9 to get merged before releasing it.

2022-12-05 14:56 UTC, tribeiro commented on python/lsst/ts/utils/__init__.py
> +from .generator import *
Consider renaming it `image_name_service_client`

2022-12-05 14:56 UTC, tribeiro commented on python/lsst/ts/utils/generator.py
> +        self.sources = {
I think you can remove this and ask the user to provide the 2 letter string. 

```
def __init__(self, url: str, csc_name: str, csc_index: int, source: str) -> None:
```

2022-12-05 14:56 UTC, tribeiro commented on python/lsst/ts/utils/generator.py
> +        self.site = os.environ["LSST_SITE"]
I don't think this information is relevant. Please remove it.

2022-12-05 14:56 UTC, tribeiro commented on python/lsst/ts/utils/generator.py
> +        if self.site == "test":
I think you can just remove this if/else statement and do:

```
            params = {
                 "n": num_images,
                 "sourceIndex": self.csc_index,
                 "source": self.source,
             }
             url = self.url
             call_url = "/ImageUtilities/rest/imageNameService"
             async with aiohttp.ClientSession(url, raise_for_status=True) as session:
                 async with session.get(url=call_url, params=params) as response:
                     fd: io.StringIO = io.StringIO()
                     async for chunk in response.content.iter_chunked(1024):
                         fd.write(chunk.decode())
                     df = json.load(fd)
                     image_sequence_array = [int(item.split("_")[-1]) for item in df]
                     return image_sequence_array, df
```

2022-12-05 15:39 UTC, couger01 commented on python/lsst/ts/utils/generator.py
> +        self.site = os.environ["LSST_SITE"]
It's only relevant for the unit test. I'd prefer just to keep it unless you really want it gone.

2022-12-05 17:25 UTC, couger01 commented on python/lsst/ts/utils/generator.py
> +        self.site = os.environ["LSST_SITE"]
Removed.

2022-12-05 19:21 UTC, r-owen commented on doc/version_history.rst
> +* Add ImageNameServiceClient class
I have merged my PR and I agree that 1.2.0 is the right version number. Thank you for updating it.

2022-12-05 19:23 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +        csc_index: int,
I may be blind, but I don't see anywhere that you use csc_name and csc_index. If you don't need them, please ditch them.

2022-12-05 19:27 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +        self.unit_test = unit_test
I gently suggest a different name. There are multiple reasons one might want to use mock data, not just unit tests. Please consider simulation_mode (an analog to CSCs) or simulate or mock_data or...

2022-12-05 19:28 UTC, r-owen commented on tests/test_image_name_service_client.py
> +        os.environ["LSST_SITE"] = "test"
I think you no longer use LSST_SITE. If that is true, please delete this line and look for all other instances of LSST_SITE as well.

2022-12-05 19:28 UTC, r-owen commented on tests/test_image_name_service_client.py
> +        assert image_sequence_array == [2]
Please also test with num_images > 1 and invalid values as well, such as 0 and -1

2022-12-05 19:29 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +            The number of images to get.
What happens if num_images < 1? Please raise an exception and document it in this doc string.

2022-12-05 19:31 UTC, r-owen commented
I'm afraid you'll have to rebase before merging. If you are willing, please consider also modernizing conda/meta.yaml (I sent a candidate version via Slack), since I didn't realize it was wanted in time to add that to my PR.

I also have a few suggestions that I made as individual commands instead of a review.

2022-12-05 20:22 UTC, couger01 commented on python/lsst/ts/utils/image_name_service_client.py
> +        csc_index: int,
I use csc_index in line 102.

2022-12-05 22:48 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +        csc_index: int,
Yes. You use csc_index in some way that seems to be an analog to source (rather than csc_name). So is the source the name of the CSC? In which case csc_name and csc_index might make more sense. Or is it something else? In which case what is sourceIndex the index of?

2022-12-05 22:50 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +            The ID used by the service for CSC verification.
Can you please provide more information? If there are a small number of these, perhaps just list them here. Or point to a document somewhere.

2022-12-05 22:51 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +            Raised when num_images is less than 1.
Thank you for adding the exception, but please consider ValueError or similar

2022-12-05 22:54 UTC, r-owen commented on python/lsst/ts/utils/image_name_service_client.py
> +            The raw json data.
Surely this is not raw json data -- json.load(fd) is supposed to read and decode the data. It is merely the decoded object, which is...what? Please document it.

(Annoying that the service doesn't provide a better json encoding, so you have to further massage the data.)

2022-12-05 22:55 UTC, r-owen commented on tests/test_image_name_service_client.py
> +        assert image_sequence_array == [2]
Thanks for the invalid values. Please also test with num_images > 1. Please test `data` as well. Since you return it, you should test it.

2022-12-06 13:37 UTC, tribeiro commented on python/lsst/ts/utils/image_name_service_client.py
> +            The ID used by the service for CSC verification.
How about something like this:

```
A 2 characters string identifying the component, e.g. AT for ATCamera.
```

2022-12-06 13:43 UTC, tribeiro commented on python/lsst/ts/utils/image_name_service_client.py
> +        summit_url : `str`
I think you can remove this...

2022-12-06 13:43 UTC, tribeiro commented on python/lsst/ts/utils/image_name_service_client.py
> +        teststand_url : `str`
Remove this one as well

2022-12-06 13:43 UTC, tribeiro commented on python/lsst/ts/utils/image_name_service_client.py
> +        mock_data: bool = False,
I think it is a bit weird that the class has to know it needs to mock data. I don't understand why you need to do this but I'd hope you would be able to mock the server for unit test and don't modify the class behavior during test, otherwise it is not really doing an appropriate test I think.

2022-12-06 13:43 UTC, tribeiro commented on python/lsst/ts/utils/image_name_service_client.py
> +        if self.mock_data:
Consider mocking a server instead of modifying the CSC behavior for testing. 

Check how Michael did it in the GenericCamera, [here](https://github.com/lsst-ts/ts_genericcamera/blob/1e142088f7c7be5f02ea5ef717b4021757aad21a/tests/test_csc.py#L232-L234).

2022-12-07 23:01 UTC, tribeiro approved these changes
Alright! looks great! thanks for the updates! can you please squash the commits before merging?

2022-12-07 23:17 UTC, merged